#!/usr/bin/env bash
# fmax_sweep.sh -- measure the fastest clock period that closes timing.
#
# Coarse steps of 1.0 ns down from 10.0 until a run fails the build gate, then
# bisection on a 0.1 ns grid between the last pass and the first fail. Every
# run is recorded in results/$SWEEP/summary.csv, and every run -- passing or
# failing -- is published under results/$SWEEP/p<period>/ by build.tcl, with
# BUILD_SCOPE.md or GATE_FAILED.md, so each row of the CSV traces to a record.
#
# A run counts as a timing failure only if build.tcl printed its gate-failure
# line. Anything else -- no Vivado, a licence error, a crash -- aborts the
# sweep, because silently scoring a crash as "does not close" would lower the
# reported Fmax. Every run must also carry the same source stamp; a tree that
# changes mid-sweep aborts it.
#
# One implementation run per period, default directives. Closure is not
# strictly monotonic in the period -- placement varies -- so the bisection
# assumes it, FMAX.md says so, and summary.csv is the evidence if it is not.
#
# The result is a fabric ceiling for this design on xc7a35tcpg236-1. The Basys
# 3 has a fixed 100 MHz oscillator and no MMCM here; anything faster is not
# usable on the board.
set -uo pipefail
cd "$(dirname "$0")/.."
# SWEEP names the result set, so a later iteration can sweep again without
# overwriting the baseline:  SWEEP=sweep_iter1 make fmax
# It must start with "sweep": the directory is deleted and replaced, and no
# other result set may be named by accident.
SWEEP="${SWEEP:-sweep}"
if ! [[ "$SWEEP" =~ ^sweep[A-Za-z0-9_]*$ ]]; then
  echo "ERROR: SWEEP='$SWEEP' must match ^sweep[A-Za-z0-9_]*\$ (e.g. sweep, sweep_iter1)." >&2
  exit 2
fi
OUT="results/$SWEEP"
rm -rf "$OUT"            # never leave an earlier sweep's Fmax looking current
mkdir -p "$OUT" build
SUMMARY="$OUT/summary.csv"
echo "period_ns,result,wns_ns,whs_ns" > "$SUMMARY"

# Periods are handled in integer tenths of a nanosecond, so the grid is exact.
fmt() { printf "%d.%d" $(( $1 / 10 )) $(( $1 % 10 )); }

SOURCE=""
run() {
  local p log rc r wns whs src
  p=$(fmt "$1"); log="build/${SWEEP}_p${p}.txt"
  make --no-print-directory build PERIOD="$p" RUN="$SWEEP/p$p" PUBLISH_FAILED=1 > "$log" 2>&1
  rc=$?
  if [ "$rc" -eq 0 ] && grep -q "^== build complete" "$log"; then
    r=pass
  elif grep -q "^== GATE FAILED ==" "$log"; then
    r=fail
  else
    echo "ABORT: the build at $p ns neither passed nor failed the gate (exit $rc); see $log" >&2
    exit 2
  fi
  src=$(cat "$OUT/p$p/BUILD_SCOPE.md" "$OUT/p$p/GATE_FAILED.md" 2>/dev/null | grep -m1 "^- Source:")
  if [ -z "$src" ]; then
    echo "ABORT: no source stamp published for $p ns; see $log" >&2
    exit 2
  fi
  if [ -z "$SOURCE" ]; then
    SOURCE="$src"
  elif [ "$src" != "$SOURCE" ]; then
    echo "ABORT: the source tree changed during the sweep ($p ns: '$src', first run: '$SOURCE')" >&2
    exit 2
  fi
  wns=$(grep -oE "WNS -?[0-9.]+ ns" "$log" | tail -1 | awk '{print $2}')
  whs=$(grep -oE "WHS -?[0-9.]+ ns" "$log" | tail -1 | awk '{print $2}')
  echo "$p,$r,${wns:-},${whs:-}" >> "$SUMMARY"
  echo "  period $p ns: $r (WNS ${wns:-n/a})"
  [ "$r" = pass ]
}

best=""; fail=""
t=100
echo "== coarse sweep"
while :; do
  if run "$t"; then
    best=$t
    [ "$t" -le 10 ] && break
    t=$(( t - 10 ))
  else
    fail=$t
    break
  fi
done
if [ -z "$best" ]; then
  echo "ERROR: 10.0 ns does not close; there is no Fmax to report." >&2
  exit 1
fi

if [ -n "$fail" ]; then
  echo "== bisection between $(fmt "$fail") (fail) and $(fmt "$best") (pass)"
  lo=$fail; hi=$best
  while [ $(( hi - lo )) -gt 1 ]; do
    mid=$(( (lo + hi) / 2 ))
    if run "$mid"; then hi=$mid; best=$mid; else lo=$mid; fi
  done
  fail_txt="fastest failing period tried: $(fmt "$lo") ns"
else
  fail_txt="no failing period found down to $(fmt "$best") ns"
fi

fmax=$(awk -v b="$best" 'BEGIN { printf "%.1f", 10000 / b }')
cat > "$OUT/FMAX.md" <<EOF
measured_fmax_mhz=$fmax period_ns=$(fmt "$best")

# Measured Fmax

Generated by scripts/fmax_sweep.sh. Do not edit by hand.

$SOURCE (identical for every run in this sweep)
- Fastest passing period: $(fmt "$best") ns ($fmax MHz); $fail_txt.
- Method: one implementation per period with default directives; coarse 1.0 ns
  steps from 10.0 ns, then bisection on a 0.1 ns grid. Each point is
  synthesized and implemented against its own period. Every run is listed in
  summary.csv and published under p<period>/.
- The bisection assumes closure is monotonic in the period. Placement varies
  between periods, so that is an assumption, not a guarantee.
- **Not usable on the Basys 3.** The board oscillator is fixed at 100 MHz and the
  design has no MMCM; this is a fabric ceiling for this design on xc7a35tcpg236-1.
- The p10.0 run is an ordinary board-period build (it writes a bitstream).
EOF
echo "== measured Fmax $fmax MHz at $(fmt "$best") ns (see $SUMMARY)"
